-- --- User actions table with event_type as string ---
DROP TABLE IF EXISTS user_actions;

CREATE TABLE IF NOT EXISTS user_actions (
    user_id INT NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    timestamp TIMESTAMP NOT NULL
);

INSERT INTO user_actions (user_id, event_type, timestamp)
VALUES
(1, 'sign-in', NOW() - interval '50 days'),
(2, 'like', NOW() - interval '49 days'),
(3, 'comment', NOW() - interval '48 days'),
(4, 'sign-in', NOW() - interval '47 days'),
(5, 'like', NOW() - interval '46 days'),
(6, 'comment', NOW() - interval '45 days'),
(1, 'like', NOW() - interval '44 days'),
(2, 'comment', NOW() - interval '43 days'),
(3, 'sign-in', NOW() - interval '42 days'),
(4, 'like', NOW() - interval '41 days'),
(5, 'comment', NOW() - interval '40 days'),
(6, 'sign-in', NOW() - interval '39 days'),
(1, 'comment', NOW() - interval '38 days'),
(2, 'sign-in', NOW() - interval '37 days'),
(3, 'like', NOW() - interval '36 days'),
(4, 'comment', NOW() - interval '35 days'),
(5, 'sign-in', NOW() - interval '34 days'),
(6, 'like', NOW() - interval '33 days'),
(1, 'sign-in', NOW() - interval '32 days'),
(2, 'comment', NOW() - interval '31 days'),
(3, 'like', NOW() - interval '30 days'),
(4, 'sign-in', NOW() - interval '29 days'),
(5, 'comment', NOW() - interval '28 days'),
(6, 'like', NOW() - interval '27 days'),
(1, 'comment', NOW() - interval '26 days'),
(2, 'sign-in', NOW() - interval '25 days'),
(3, 'like', NOW() - interval '24 days'),
(4, 'comment', NOW() - interval '23 days'),
(5, 'sign-in', NOW() - interval '22 days'),
(6, 'like', NOW() - interval '21 days'),
(1, 'sign-in', NOW() - interval '20 days'),
(2, 'comment', NOW() - interval '19 days'),
(3, 'like', NOW() - interval '18 days'),
(4, 'sign-in', NOW() - interval '17 days'),
(5, 'comment', NOW() - interval '16 days'),
(6, 'like', NOW() - interval '15 days'),
(1, 'comment', NOW() - interval '14 days'),
(2, 'sign-in', NOW() - interval '13 days'),
(3, 'like', NOW() - interval '12 days'),
(4, 'comment', NOW() - interval '11 days'),
(5, 'sign-in', NOW() - interval '10 days'),
(6, 'like', NOW() - interval '9 days'),
(1, 'sign-in', NOW() - interval '8 days'),
(2, 'comment', NOW() - interval '7 days'),
(3, 'like', NOW() - interval '6 days'),
(4, 'sign-in', NOW() - interval '5 days'),
(5, 'comment', NOW() - interval '4 days'),
(6, 'like', NOW() - interval '3 days'),
(1, 'comment', NOW() - interval '2 days'),
(2, 'sign-in', NOW() - interval '1 day');
