-- --- Activities table ---
DROP TABLE IF EXISTS activities;

-- Table
CREATE TABLE IF NOT EXISTS activities (
    activity_id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    type VARCHAR(20) NOT NULL,
    time_spent INT NOT NULL, 
    activity_date TIMESTAMP NOT NULL
);

-- Values
INSERT INTO activities (user_id, type, time_spent, activity_date)
VALUES
(1, 'sending', 30, NOW() - interval '50 days'),
(2, 'opening', 45, NOW() - interval '49 days'),
(3, 'chatting', 60, NOW() - interval '48 days'),
(4, 'story_view', 90, NOW() - interval '47 days'),
(5, 'story_post', 25, NOW() - interval '46 days'),
(6, 'discover', 35, NOW() - interval '45 days'),
(1, 'sending', 40, NOW() - interval '44 days'),
(2, 'opening', 50, NOW() - interval '43 days'),
(3, 'chatting', 20, NOW() - interval '42 days'),
(4, 'story_view', 55, NOW() - interval '41 days'),
(5, 'story_post', 65, NOW() - interval '40 days'),
(6, 'discover', 70, NOW() - interval '39 days'),
(1, 'sending', 30, NOW() - interval '38 days'),
(2, 'opening', 45, NOW() - interval '37 days'),
(3, 'chatting', 60, NOW() - interval '36 days'),
(4, 'story_view', 90, NOW() - interval '35 days'),
(5, 'story_post', 25, NOW() - interval '34 days'),
(6, 'discover', 35, NOW() - interval '33 days'),
(1, 'sending', 40, NOW() - interval '32 days'),
(2, 'opening', 50, NOW() - interval '31 days'),
(3, 'chatting', 20, NOW() - interval '30 days'),
(4, 'story_view', 55, NOW() - interval '29 days'),
(5, 'story_post', 65, NOW() - interval '28 days'),
(6, 'discover', 70, NOW() - interval '27 days'),
(1, 'sending', 30, NOW() - interval '26 days'),
(2, 'opening', 45, NOW() - interval '25 days'),
(3, 'chatting', 60, NOW() - interval '24 days'),
(4, 'story_view', 90, NOW() - interval '23 days'),
(5, 'story_post', 25, NOW() - interval '22 days'),
(6, 'discover', 35, NOW() - interval '21 days'),
(1, 'sending', 40, NOW() - interval '20 days'),
(2, 'opening', 50, NOW() - interval '19 days'),
(3, 'chatting', 20, NOW() - interval '18 days'),
(4, 'story_view', 55, NOW() - interval '17 days'),
(5, 'story_post', 65, NOW() - interval '16 days'),
(6, 'discover', 70, NOW() - interval '15 days'),
(1, 'sending', 30, NOW() - interval '14 days'),
(2, 'opening', 45, NOW() - interval '13 days'),
(3, 'chatting', 60, NOW() - interval '12 days'),
(4, 'story_view', 90, NOW() - interval '11 days'),
(5, 'story_post', 25, NOW() - interval '10 days'),
(6, 'discover', 35, NOW() - interval '9 days'),
(1, 'sending', 40, NOW() - interval '8 days'),
(2, 'opening', 50, NOW() - interval '7 days'),
(3, 'chatting', 20, NOW() - interval '6 days'),
(4, 'story_view', 55, NOW() - interval '5 days'),
(5, 'story_post', 65, NOW() - interval '4 days'),
(6, 'discover', 70, NOW() - interval '3 days'),
(1, 'sending', 30, NOW() - interval '2 days'),
(2, 'opening', 45, NOW() - interval '1 day');
